# ------------------------------------------------------------------------------
# SPDX-License-Identifier: MIT OR GPL-3.0-or-later
# Copyright (C) 2021 Stepan Nassyr <s.nassyr@fz-juelich.de>
# Copyright (C) 2021 Stepan Nassyr <s.nassyr@xcpp.org>
# ------------------------------------------------------------------------------

import datetime
import logging
import os
import sys
import tempfile

import yaml
from git import Repo

from argparse import ArgumentParser

from ukrgen.codegen.isa_compiler_support import isa_flags
from ukrgen.injectors.blis.patcher import blis_patcher

def blisgen():

    parser = ArgumentParser()

    parser.add_argument("--debug",
                        help="Enable debug information",
                        action="store_true")

    kernels = ["sgemm","dgemm"]
    for k in kernels:
        parser.add_argument(f"--{k}-config",
                            help=f"file containing the configuration for {k}",
                            type=str,
                            required=True)

    parser.add_argument("--config-name",
                        help="name of the blis config (default: ukrgen_<isa>)",
                        type=str,
                        required=False)

    source_group = parser.add_mutually_exclusive_group(required=True)
    source_group.add_argument("--from-dir",
                              help="generate blis using the source in the specified directory",
                              type=str)
    source_group.add_argument("--from-git",
                              help="generate blis using the source in the specified git repository URL",
                              type=str)

    parser.add_argument("--temp-dir",
                        help="Directory to put temporary files in (default: autogenerated)",
                        type=str,
                        required=False)

    parser.add_argument("--out-dir",
                        help="directory to output the generated source to",
                        type=str,
                        required=True)

    parser.add_argument("--author",
                        help="Author to insert in the copyright string",
                        type=str,
                        required=True)



    args,rest = parser.parse_known_args()

    if args.debug:
        logging.basicConfig(level=logging.DEBUG)


    with open(args.sgemm_config, "r") as sf:
        sgemm_config = yaml.safe_load(sf)
    with open(args.dgemm_config, "r") as df:
        dgemm_config = yaml.safe_load(df)

    # TODO: compatible ISAs (sme<->sve<->neon, avx512<->avx2, etc...)
    assert(sgemm_config["isa"] == dgemm_config["isa"])

    isa = sgemm_config["isa"]

    blis_dir = ""
    if args.from_git is not None:
        temp_dir = ""
        if args.temp_dir:
            temp_dir = args.temp_dir
        else:
            temp_dir = tempfile.TemporaryDirectory().name
        blis_dir = os.path.join(temp_dir,"vanillablis")
        Repo.clone_from("https://github.com/flame/blis", blis_dir)
    else:
        blis_dir = args.from_dir

    configname=f"ukrgen_{isa}"
    if args.config_name is not None:
        configname = args.config_name

    bp = blis_patcher()

    blis_params = {
        "year" : datetime.datetime.today().strftime("%Y"),
        "author" : args.author,
        "configname" : configname,
        "cntx_extra_defs" : "",
        "cntx_init_extra" : "",
        "simd_size" : "get_simd_size()",
        "archflags" : isa_flags[isa],
    }

    bp.make_kernels([sgemm_config,dgemm_config],
                    blis_params)


    bp.prepare_code(blis_params)

    bp.patch(blis_dir, args.out_dir)


if __name__ == "__main__":
    blisgen()
